version: '3'

services:
  phpfpm:
    image: 'bitnami/php-fpm:latest'
    expose:
      - "9000"
    volumes:
      - type: bind
        source: ./
        target: /app
  nginx:
    image: 'bitnami/nginx:latest'
    ports:
      - '80:80'
    volumes:
      - type: bind
        source: ./nginx/myapp.conf
        target: /opt/bitnami/nginx/conf/server_blocks/myapp.conf
      - type: bind
        source: ./
        target: /var/www/